name: nyc_taxi_analytics
version: "1.0.0"
config-version: 2

profile: nyc_taxi_analytics

model-paths:
  - models

clean-targets:
  - target
  - dbt_packages

models:
  nyc_taxi_analytics:
    staging:
      +materialized: "{{ 'ephemeral' if target.type == 'databricks' else 'view' }}"

    intermediate:
      +materialized: "{{ 'ephemeral' if target.type == 'databricks' else 'view' }}"

    marts:
      +materialized: table
